DATA_SIMULASI = [
    {"nama_usaha": "Warung Ibu Siti", "lokasi": "Bandung", "barang": "Beras Pandan Wangi", "kuantitas": 50, "unit": "kg"},
    {"nama_usaha": "Warung Pak Budi", "lokasi": "Bandung", "barang": "Gula Pasir", "kuantitas": 20, "unit": "kg"},
    {"nama_usaha": "Bakso Mang Ujang", "lokasi": "Bandung", "barang": "Tepung Tapioka", "kuantitas": 30, "unit": "kg"},
    {"nama_usaha": "Toko Roti Manis", "lokasi": "Jakarta", "barang": "Tepung Terigu", "kuantitas": 40, "unit": "kg"},
    {"nama_usaha": "Kopi Senja", "lokasi": "Jakarta", "barang": "Kopi Robusta", "kuantitas": 10, "unit": "kg"},
    {"nama_usaha": "Es Teh Segar", "lokasi": "Bandung", "barang": "Gula Pasir", "kuantitas": 15, "unit": "kg"},
    {"nama_usaha": "Catering Bu Lilis", "lokasi": "Jakarta", "barang": "Minyak Goreng", "kuantitas": 50, "unit": "liter"},
    {"nama_usaha": "Sate Madura Pak Joko", "lokasi": "Surabaya", "barang": "Kecap Manis", "kuantitas": 25, "unit": "liter"},
    {"nama_usaha": "Warung Nasi Padang Uni Ria", "lokasi": "Bandung", "barang": "Beras Pandan Wangi", "kuantitas": 80, "unit": "kg"},
    {"nama_usaha": "Ayam Geprek Mantul", "lokasi": "Jakarta", "barang": "Minyak Goreng", "kuantitas": 30, "unit": "liter"},
    {"nama_usaha": "Rujak Cingur Pak Dani", "lokasi": "Surabaya", "barang": "Gula Merah", "kuantitas": 10, "unit": "kg"},
    {"nama_usaha": "Bubur Ayam Mang Asep", "lokasi": "Bandung", "barang": "Beras Pandan Wangi", "kuantitas": 60, "unit": "kg"},
    {"nama_usaha": "Warung Tegal Barokah", "lokasi": "Jakarta", "barang": "Tepung Terigu", "kuantitas": 20, "unit": "kg"},
    {"nama_usaha": "Soto Ayam Pakde", "lokasi": "Surabaya", "barang": "Bawang Merah", "kuantitas": 15, "unit": "kg"},
]